# Generated by Django 4.1.1 on 2022-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_librarian",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user belongs to the authorized library staff.",
                verbose_name="Librarian",
            ),
        ),
    ]
